/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the ExpectedSwitchUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedSwitchUpdateRequest{}

// ExpectedSwitchUpdateRequest Request data to update an existing Expected Switch.  Note: BMC and NvOS credentials (username/password) are only accepted during creation and updates but are not returned in responses.
type ExpectedSwitchUpdateRequest struct {
	// ID of the Expected Switch to update (ignored for single update, used for identification in batch operations).
	Id NullableString `json:"id,omitempty"`
	// MAC address of the Expected Switch's BMC (Baseboard Management Controller)
	BmcMacAddress NullableString `json:"bmcMacAddress,omitempty" validate:"regexp=^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$"`
	// Username for accessing the Expected Switch's BMC
	DefaultBmcUsername NullableString `json:"defaultBmcUsername,omitempty"`
	// Password for accessing the Expected Switch's BMC
	DefaultBmcPassword NullableString `json:"defaultBmcPassword,omitempty"`
	// Serial number of the Expected Switch
	SwitchSerialNumber NullableString `json:"switchSerialNumber,omitempty"`
	// NvOS username for the Expected Switch
	NvOsUsername NullableString `json:"nvOsUsername,omitempty"`
	// NvOS password for the Expected Switch
	NvOsPassword NullableString    `json:"nvOsPassword,omitempty"`
	Labels       map[string]string `json:"labels,omitempty"`
}

// NewExpectedSwitchUpdateRequest instantiates a new ExpectedSwitchUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedSwitchUpdateRequest() *ExpectedSwitchUpdateRequest {
	this := ExpectedSwitchUpdateRequest{}
	return &this
}

// NewExpectedSwitchUpdateRequestWithDefaults instantiates a new ExpectedSwitchUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedSwitchUpdateRequestWithDefaults() *ExpectedSwitchUpdateRequest {
	this := ExpectedSwitchUpdateRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedSwitchUpdateRequest) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedSwitchUpdateRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *ExpectedSwitchUpdateRequest) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *ExpectedSwitchUpdateRequest) SetId(v string) {
	o.Id.Set(&v)
}

// SetIdNil sets the value for Id to be an explicit nil
func (o *ExpectedSwitchUpdateRequest) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *ExpectedSwitchUpdateRequest) UnsetId() {
	o.Id.Unset()
}

// GetBmcMacAddress returns the BmcMacAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedSwitchUpdateRequest) GetBmcMacAddress() string {
	if o == nil || IsNil(o.BmcMacAddress.Get()) {
		var ret string
		return ret
	}
	return *o.BmcMacAddress.Get()
}

// GetBmcMacAddressOk returns a tuple with the BmcMacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedSwitchUpdateRequest) GetBmcMacAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BmcMacAddress.Get(), o.BmcMacAddress.IsSet()
}

// HasBmcMacAddress returns a boolean if a field has been set.
func (o *ExpectedSwitchUpdateRequest) HasBmcMacAddress() bool {
	if o != nil && o.BmcMacAddress.IsSet() {
		return true
	}

	return false
}

// SetBmcMacAddress gets a reference to the given NullableString and assigns it to the BmcMacAddress field.
func (o *ExpectedSwitchUpdateRequest) SetBmcMacAddress(v string) {
	o.BmcMacAddress.Set(&v)
}

// SetBmcMacAddressNil sets the value for BmcMacAddress to be an explicit nil
func (o *ExpectedSwitchUpdateRequest) SetBmcMacAddressNil() {
	o.BmcMacAddress.Set(nil)
}

// UnsetBmcMacAddress ensures that no value is present for BmcMacAddress, not even an explicit nil
func (o *ExpectedSwitchUpdateRequest) UnsetBmcMacAddress() {
	o.BmcMacAddress.Unset()
}

// GetDefaultBmcUsername returns the DefaultBmcUsername field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedSwitchUpdateRequest) GetDefaultBmcUsername() string {
	if o == nil || IsNil(o.DefaultBmcUsername.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultBmcUsername.Get()
}

// GetDefaultBmcUsernameOk returns a tuple with the DefaultBmcUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedSwitchUpdateRequest) GetDefaultBmcUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultBmcUsername.Get(), o.DefaultBmcUsername.IsSet()
}

// HasDefaultBmcUsername returns a boolean if a field has been set.
func (o *ExpectedSwitchUpdateRequest) HasDefaultBmcUsername() bool {
	if o != nil && o.DefaultBmcUsername.IsSet() {
		return true
	}

	return false
}

// SetDefaultBmcUsername gets a reference to the given NullableString and assigns it to the DefaultBmcUsername field.
func (o *ExpectedSwitchUpdateRequest) SetDefaultBmcUsername(v string) {
	o.DefaultBmcUsername.Set(&v)
}

// SetDefaultBmcUsernameNil sets the value for DefaultBmcUsername to be an explicit nil
func (o *ExpectedSwitchUpdateRequest) SetDefaultBmcUsernameNil() {
	o.DefaultBmcUsername.Set(nil)
}

// UnsetDefaultBmcUsername ensures that no value is present for DefaultBmcUsername, not even an explicit nil
func (o *ExpectedSwitchUpdateRequest) UnsetDefaultBmcUsername() {
	o.DefaultBmcUsername.Unset()
}

// GetDefaultBmcPassword returns the DefaultBmcPassword field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedSwitchUpdateRequest) GetDefaultBmcPassword() string {
	if o == nil || IsNil(o.DefaultBmcPassword.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultBmcPassword.Get()
}

// GetDefaultBmcPasswordOk returns a tuple with the DefaultBmcPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedSwitchUpdateRequest) GetDefaultBmcPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultBmcPassword.Get(), o.DefaultBmcPassword.IsSet()
}

// HasDefaultBmcPassword returns a boolean if a field has been set.
func (o *ExpectedSwitchUpdateRequest) HasDefaultBmcPassword() bool {
	if o != nil && o.DefaultBmcPassword.IsSet() {
		return true
	}

	return false
}

// SetDefaultBmcPassword gets a reference to the given NullableString and assigns it to the DefaultBmcPassword field.
func (o *ExpectedSwitchUpdateRequest) SetDefaultBmcPassword(v string) {
	o.DefaultBmcPassword.Set(&v)
}

// SetDefaultBmcPasswordNil sets the value for DefaultBmcPassword to be an explicit nil
func (o *ExpectedSwitchUpdateRequest) SetDefaultBmcPasswordNil() {
	o.DefaultBmcPassword.Set(nil)
}

// UnsetDefaultBmcPassword ensures that no value is present for DefaultBmcPassword, not even an explicit nil
func (o *ExpectedSwitchUpdateRequest) UnsetDefaultBmcPassword() {
	o.DefaultBmcPassword.Unset()
}

// GetSwitchSerialNumber returns the SwitchSerialNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedSwitchUpdateRequest) GetSwitchSerialNumber() string {
	if o == nil || IsNil(o.SwitchSerialNumber.Get()) {
		var ret string
		return ret
	}
	return *o.SwitchSerialNumber.Get()
}

// GetSwitchSerialNumberOk returns a tuple with the SwitchSerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedSwitchUpdateRequest) GetSwitchSerialNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SwitchSerialNumber.Get(), o.SwitchSerialNumber.IsSet()
}

// HasSwitchSerialNumber returns a boolean if a field has been set.
func (o *ExpectedSwitchUpdateRequest) HasSwitchSerialNumber() bool {
	if o != nil && o.SwitchSerialNumber.IsSet() {
		return true
	}

	return false
}

// SetSwitchSerialNumber gets a reference to the given NullableString and assigns it to the SwitchSerialNumber field.
func (o *ExpectedSwitchUpdateRequest) SetSwitchSerialNumber(v string) {
	o.SwitchSerialNumber.Set(&v)
}

// SetSwitchSerialNumberNil sets the value for SwitchSerialNumber to be an explicit nil
func (o *ExpectedSwitchUpdateRequest) SetSwitchSerialNumberNil() {
	o.SwitchSerialNumber.Set(nil)
}

// UnsetSwitchSerialNumber ensures that no value is present for SwitchSerialNumber, not even an explicit nil
func (o *ExpectedSwitchUpdateRequest) UnsetSwitchSerialNumber() {
	o.SwitchSerialNumber.Unset()
}

// GetNvOsUsername returns the NvOsUsername field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedSwitchUpdateRequest) GetNvOsUsername() string {
	if o == nil || IsNil(o.NvOsUsername.Get()) {
		var ret string
		return ret
	}
	return *o.NvOsUsername.Get()
}

// GetNvOsUsernameOk returns a tuple with the NvOsUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedSwitchUpdateRequest) GetNvOsUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NvOsUsername.Get(), o.NvOsUsername.IsSet()
}

// HasNvOsUsername returns a boolean if a field has been set.
func (o *ExpectedSwitchUpdateRequest) HasNvOsUsername() bool {
	if o != nil && o.NvOsUsername.IsSet() {
		return true
	}

	return false
}

// SetNvOsUsername gets a reference to the given NullableString and assigns it to the NvOsUsername field.
func (o *ExpectedSwitchUpdateRequest) SetNvOsUsername(v string) {
	o.NvOsUsername.Set(&v)
}

// SetNvOsUsernameNil sets the value for NvOsUsername to be an explicit nil
func (o *ExpectedSwitchUpdateRequest) SetNvOsUsernameNil() {
	o.NvOsUsername.Set(nil)
}

// UnsetNvOsUsername ensures that no value is present for NvOsUsername, not even an explicit nil
func (o *ExpectedSwitchUpdateRequest) UnsetNvOsUsername() {
	o.NvOsUsername.Unset()
}

// GetNvOsPassword returns the NvOsPassword field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedSwitchUpdateRequest) GetNvOsPassword() string {
	if o == nil || IsNil(o.NvOsPassword.Get()) {
		var ret string
		return ret
	}
	return *o.NvOsPassword.Get()
}

// GetNvOsPasswordOk returns a tuple with the NvOsPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedSwitchUpdateRequest) GetNvOsPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NvOsPassword.Get(), o.NvOsPassword.IsSet()
}

// HasNvOsPassword returns a boolean if a field has been set.
func (o *ExpectedSwitchUpdateRequest) HasNvOsPassword() bool {
	if o != nil && o.NvOsPassword.IsSet() {
		return true
	}

	return false
}

// SetNvOsPassword gets a reference to the given NullableString and assigns it to the NvOsPassword field.
func (o *ExpectedSwitchUpdateRequest) SetNvOsPassword(v string) {
	o.NvOsPassword.Set(&v)
}

// SetNvOsPasswordNil sets the value for NvOsPassword to be an explicit nil
func (o *ExpectedSwitchUpdateRequest) SetNvOsPasswordNil() {
	o.NvOsPassword.Set(nil)
}

// UnsetNvOsPassword ensures that no value is present for NvOsPassword, not even an explicit nil
func (o *ExpectedSwitchUpdateRequest) UnsetNvOsPassword() {
	o.NvOsPassword.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ExpectedSwitchUpdateRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedSwitchUpdateRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ExpectedSwitchUpdateRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *ExpectedSwitchUpdateRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

func (o ExpectedSwitchUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedSwitchUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if o.BmcMacAddress.IsSet() {
		toSerialize["bmcMacAddress"] = o.BmcMacAddress.Get()
	}
	if o.DefaultBmcUsername.IsSet() {
		toSerialize["defaultBmcUsername"] = o.DefaultBmcUsername.Get()
	}
	if o.DefaultBmcPassword.IsSet() {
		toSerialize["defaultBmcPassword"] = o.DefaultBmcPassword.Get()
	}
	if o.SwitchSerialNumber.IsSet() {
		toSerialize["switchSerialNumber"] = o.SwitchSerialNumber.Get()
	}
	if o.NvOsUsername.IsSet() {
		toSerialize["nvOsUsername"] = o.NvOsUsername.Get()
	}
	if o.NvOsPassword.IsSet() {
		toSerialize["nvOsPassword"] = o.NvOsPassword.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

type NullableExpectedSwitchUpdateRequest struct {
	value *ExpectedSwitchUpdateRequest
	isSet bool
}

func (v NullableExpectedSwitchUpdateRequest) Get() *ExpectedSwitchUpdateRequest {
	return v.value
}

func (v *NullableExpectedSwitchUpdateRequest) Set(val *ExpectedSwitchUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedSwitchUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedSwitchUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedSwitchUpdateRequest(val *ExpectedSwitchUpdateRequest) *NullableExpectedSwitchUpdateRequest {
	return &NullableExpectedSwitchUpdateRequest{value: val, isSet: true}
}

func (v NullableExpectedSwitchUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedSwitchUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
