/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"time"
)

// checks if the ExpectedSwitch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedSwitch{}

// ExpectedSwitch An Expected Switch represents a network switch that is expected to be discovered at a site, with hardware identifiers and metadata.  Note: BMC and NvOS credentials (username/password) are only accepted during creation and updates but are not returned in responses.
type ExpectedSwitch struct {
	// Unique identifier for the Expected Switch
	Id *string `json:"id,omitempty"`
	// ID of the site the Expected Switch belongs to
	SiteId *string `json:"siteId,omitempty"`
	// MAC address of the Expected Switch's BMC (Baseboard Management Controller)
	BmcMacAddress *string `json:"bmcMacAddress,omitempty" validate:"regexp=^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$"`
	// Serial number of the Expected Switch
	SwitchSerialNumber *string           `json:"switchSerialNumber,omitempty"`
	Labels             map[string]string `json:"labels,omitempty"`
	// ISO 8601 datetime when the Expected Switch was created
	Created *time.Time `json:"created,omitempty"`
	// ISO 8601 datetime when the Expected Switch was last updated
	Updated *time.Time `json:"updated,omitempty"`
}

// NewExpectedSwitch instantiates a new ExpectedSwitch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedSwitch() *ExpectedSwitch {
	this := ExpectedSwitch{}
	return &this
}

// NewExpectedSwitchWithDefaults instantiates a new ExpectedSwitch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedSwitchWithDefaults() *ExpectedSwitch {
	this := ExpectedSwitch{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ExpectedSwitch) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedSwitch) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ExpectedSwitch) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ExpectedSwitch) SetId(v string) {
	o.Id = &v
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *ExpectedSwitch) GetSiteId() string {
	if o == nil || IsNil(o.SiteId) {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedSwitch) GetSiteIdOk() (*string, bool) {
	if o == nil || IsNil(o.SiteId) {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *ExpectedSwitch) HasSiteId() bool {
	if o != nil && !IsNil(o.SiteId) {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *ExpectedSwitch) SetSiteId(v string) {
	o.SiteId = &v
}

// GetBmcMacAddress returns the BmcMacAddress field value if set, zero value otherwise.
func (o *ExpectedSwitch) GetBmcMacAddress() string {
	if o == nil || IsNil(o.BmcMacAddress) {
		var ret string
		return ret
	}
	return *o.BmcMacAddress
}

// GetBmcMacAddressOk returns a tuple with the BmcMacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedSwitch) GetBmcMacAddressOk() (*string, bool) {
	if o == nil || IsNil(o.BmcMacAddress) {
		return nil, false
	}
	return o.BmcMacAddress, true
}

// HasBmcMacAddress returns a boolean if a field has been set.
func (o *ExpectedSwitch) HasBmcMacAddress() bool {
	if o != nil && !IsNil(o.BmcMacAddress) {
		return true
	}

	return false
}

// SetBmcMacAddress gets a reference to the given string and assigns it to the BmcMacAddress field.
func (o *ExpectedSwitch) SetBmcMacAddress(v string) {
	o.BmcMacAddress = &v
}

// GetSwitchSerialNumber returns the SwitchSerialNumber field value if set, zero value otherwise.
func (o *ExpectedSwitch) GetSwitchSerialNumber() string {
	if o == nil || IsNil(o.SwitchSerialNumber) {
		var ret string
		return ret
	}
	return *o.SwitchSerialNumber
}

// GetSwitchSerialNumberOk returns a tuple with the SwitchSerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedSwitch) GetSwitchSerialNumberOk() (*string, bool) {
	if o == nil || IsNil(o.SwitchSerialNumber) {
		return nil, false
	}
	return o.SwitchSerialNumber, true
}

// HasSwitchSerialNumber returns a boolean if a field has been set.
func (o *ExpectedSwitch) HasSwitchSerialNumber() bool {
	if o != nil && !IsNil(o.SwitchSerialNumber) {
		return true
	}

	return false
}

// SetSwitchSerialNumber gets a reference to the given string and assigns it to the SwitchSerialNumber field.
func (o *ExpectedSwitch) SetSwitchSerialNumber(v string) {
	o.SwitchSerialNumber = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ExpectedSwitch) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedSwitch) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ExpectedSwitch) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *ExpectedSwitch) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *ExpectedSwitch) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedSwitch) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *ExpectedSwitch) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *ExpectedSwitch) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *ExpectedSwitch) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedSwitch) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *ExpectedSwitch) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *ExpectedSwitch) SetUpdated(v time.Time) {
	o.Updated = &v
}

func (o ExpectedSwitch) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedSwitch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.SiteId) {
		toSerialize["siteId"] = o.SiteId
	}
	if !IsNil(o.BmcMacAddress) {
		toSerialize["bmcMacAddress"] = o.BmcMacAddress
	}
	if !IsNil(o.SwitchSerialNumber) {
		toSerialize["switchSerialNumber"] = o.SwitchSerialNumber
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

type NullableExpectedSwitch struct {
	value *ExpectedSwitch
	isSet bool
}

func (v NullableExpectedSwitch) Get() *ExpectedSwitch {
	return v.value
}

func (v *NullableExpectedSwitch) Set(val *ExpectedSwitch) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedSwitch) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedSwitch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedSwitch(val *ExpectedSwitch) *NullableExpectedSwitch {
	return &NullableExpectedSwitch{value: val, isSet: true}
}

func (v NullableExpectedSwitch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedSwitch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
