/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"time"
)

// checks if the ExpectedPowerShelf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedPowerShelf{}

// ExpectedPowerShelf An Expected Power Shelf represents a power shelf that is expected to be discovered at a site, with hardware identifiers and metadata.  Note: BMC credentials (username/password) are only accepted during creation and updates but are not returned in responses.
type ExpectedPowerShelf struct {
	// Unique identifier for the Expected Power Shelf
	Id *string `json:"id,omitempty"`
	// ID of the site the Expected Power Shelf belongs to
	SiteId *string `json:"siteId,omitempty"`
	// MAC address of the Expected Power Shelf's BMC (Baseboard Management Controller)
	BmcMacAddress *string `json:"bmcMacAddress,omitempty" validate:"regexp=^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$"`
	// Serial number of the Expected Power Shelf
	ShelfSerialNumber *string `json:"shelfSerialNumber,omitempty"`
	// IP address of the Expected Power Shelf
	IpAddress NullableString    `json:"ipAddress,omitempty"`
	Labels    map[string]string `json:"labels,omitempty"`
	// ISO 8601 datetime when the Expected Power Shelf was created
	Created *time.Time `json:"created,omitempty"`
	// ISO 8601 datetime when the Expected Power Shelf was last updated
	Updated *time.Time `json:"updated,omitempty"`
}

// NewExpectedPowerShelf instantiates a new ExpectedPowerShelf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedPowerShelf() *ExpectedPowerShelf {
	this := ExpectedPowerShelf{}
	return &this
}

// NewExpectedPowerShelfWithDefaults instantiates a new ExpectedPowerShelf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedPowerShelfWithDefaults() *ExpectedPowerShelf {
	this := ExpectedPowerShelf{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ExpectedPowerShelf) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedPowerShelf) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ExpectedPowerShelf) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ExpectedPowerShelf) SetId(v string) {
	o.Id = &v
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *ExpectedPowerShelf) GetSiteId() string {
	if o == nil || IsNil(o.SiteId) {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedPowerShelf) GetSiteIdOk() (*string, bool) {
	if o == nil || IsNil(o.SiteId) {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *ExpectedPowerShelf) HasSiteId() bool {
	if o != nil && !IsNil(o.SiteId) {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *ExpectedPowerShelf) SetSiteId(v string) {
	o.SiteId = &v
}

// GetBmcMacAddress returns the BmcMacAddress field value if set, zero value otherwise.
func (o *ExpectedPowerShelf) GetBmcMacAddress() string {
	if o == nil || IsNil(o.BmcMacAddress) {
		var ret string
		return ret
	}
	return *o.BmcMacAddress
}

// GetBmcMacAddressOk returns a tuple with the BmcMacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedPowerShelf) GetBmcMacAddressOk() (*string, bool) {
	if o == nil || IsNil(o.BmcMacAddress) {
		return nil, false
	}
	return o.BmcMacAddress, true
}

// HasBmcMacAddress returns a boolean if a field has been set.
func (o *ExpectedPowerShelf) HasBmcMacAddress() bool {
	if o != nil && !IsNil(o.BmcMacAddress) {
		return true
	}

	return false
}

// SetBmcMacAddress gets a reference to the given string and assigns it to the BmcMacAddress field.
func (o *ExpectedPowerShelf) SetBmcMacAddress(v string) {
	o.BmcMacAddress = &v
}

// GetShelfSerialNumber returns the ShelfSerialNumber field value if set, zero value otherwise.
func (o *ExpectedPowerShelf) GetShelfSerialNumber() string {
	if o == nil || IsNil(o.ShelfSerialNumber) {
		var ret string
		return ret
	}
	return *o.ShelfSerialNumber
}

// GetShelfSerialNumberOk returns a tuple with the ShelfSerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedPowerShelf) GetShelfSerialNumberOk() (*string, bool) {
	if o == nil || IsNil(o.ShelfSerialNumber) {
		return nil, false
	}
	return o.ShelfSerialNumber, true
}

// HasShelfSerialNumber returns a boolean if a field has been set.
func (o *ExpectedPowerShelf) HasShelfSerialNumber() bool {
	if o != nil && !IsNil(o.ShelfSerialNumber) {
		return true
	}

	return false
}

// SetShelfSerialNumber gets a reference to the given string and assigns it to the ShelfSerialNumber field.
func (o *ExpectedPowerShelf) SetShelfSerialNumber(v string) {
	o.ShelfSerialNumber = &v
}

// GetIpAddress returns the IpAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelf) GetIpAddress() string {
	if o == nil || IsNil(o.IpAddress.Get()) {
		var ret string
		return ret
	}
	return *o.IpAddress.Get()
}

// GetIpAddressOk returns a tuple with the IpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelf) GetIpAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IpAddress.Get(), o.IpAddress.IsSet()
}

// HasIpAddress returns a boolean if a field has been set.
func (o *ExpectedPowerShelf) HasIpAddress() bool {
	if o != nil && o.IpAddress.IsSet() {
		return true
	}

	return false
}

// SetIpAddress gets a reference to the given NullableString and assigns it to the IpAddress field.
func (o *ExpectedPowerShelf) SetIpAddress(v string) {
	o.IpAddress.Set(&v)
}

// SetIpAddressNil sets the value for IpAddress to be an explicit nil
func (o *ExpectedPowerShelf) SetIpAddressNil() {
	o.IpAddress.Set(nil)
}

// UnsetIpAddress ensures that no value is present for IpAddress, not even an explicit nil
func (o *ExpectedPowerShelf) UnsetIpAddress() {
	o.IpAddress.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ExpectedPowerShelf) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedPowerShelf) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ExpectedPowerShelf) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *ExpectedPowerShelf) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *ExpectedPowerShelf) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedPowerShelf) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *ExpectedPowerShelf) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *ExpectedPowerShelf) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *ExpectedPowerShelf) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedPowerShelf) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *ExpectedPowerShelf) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *ExpectedPowerShelf) SetUpdated(v time.Time) {
	o.Updated = &v
}

func (o ExpectedPowerShelf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedPowerShelf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.SiteId) {
		toSerialize["siteId"] = o.SiteId
	}
	if !IsNil(o.BmcMacAddress) {
		toSerialize["bmcMacAddress"] = o.BmcMacAddress
	}
	if !IsNil(o.ShelfSerialNumber) {
		toSerialize["shelfSerialNumber"] = o.ShelfSerialNumber
	}
	if o.IpAddress.IsSet() {
		toSerialize["ipAddress"] = o.IpAddress.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

type NullableExpectedPowerShelf struct {
	value *ExpectedPowerShelf
	isSet bool
}

func (v NullableExpectedPowerShelf) Get() *ExpectedPowerShelf {
	return v.value
}

func (v *NullableExpectedPowerShelf) Set(val *ExpectedPowerShelf) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedPowerShelf) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedPowerShelf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedPowerShelf(val *ExpectedPowerShelf) *NullableExpectedPowerShelf {
	return &NullableExpectedPowerShelf{value: val, isSet: true}
}

func (v NullableExpectedPowerShelf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedPowerShelf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
