/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"time"
)

// checks if the ExpectedMachine type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedMachine{}

// ExpectedMachine An Expected Machine represents a physical machine that is expected to be discovered at a site, with hardware identifiers and metadata.  Note: BMC credentials (username/password) are only accepted during creation and updates but are not returned in responses.
type ExpectedMachine struct {
	// Unique identifier for the Expected Machine
	Id *string `json:"id,omitempty"`
	// ID of the site the Expected Machine belongs to
	SiteId *string `json:"siteId,omitempty"`
	// MAC address of the Expected Machine's BMC (Baseboard Management Controller)
	BmcMacAddress *string `json:"bmcMacAddress,omitempty" validate:"regexp=^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$"`
	// Serial number of the Expected Machine's chassis
	ChassisSerialNumber *string `json:"chassisSerialNumber,omitempty"`
	// Serial numbers of the Expected Machine's fallback DPUs (Data Processing Units)
	FallbackDPUSerialNumbers []string `json:"fallbackDPUSerialNumbers,omitempty"`
	// Optional ID of the SKU associated with this Expected Machine
	SkuId NullableString `json:"skuId,omitempty"`
	// SKU information for this Expected Machine (populated when includeRelation=Sku is specified)
	Sku *Sku `json:"sku,omitempty"`
	// Optional ID of the Machine associated with this Expected Machine
	MachineId NullableString `json:"machineId,omitempty"`
	// Machine information for this Expected Machine (populated when includeRelation=Machine is specified)
	Machine *MachineSummary   `json:"machine,omitempty"`
	Labels  map[string]string `json:"labels,omitempty"`
	// ISO 8601 datetime when the Expected Machine was created
	Created *time.Time `json:"created,omitempty"`
	// ISO 8601 datetime when the Expected Machine was last updated
	Updated *time.Time `json:"updated,omitempty"`
}

// NewExpectedMachine instantiates a new ExpectedMachine object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedMachine() *ExpectedMachine {
	this := ExpectedMachine{}
	return &this
}

// NewExpectedMachineWithDefaults instantiates a new ExpectedMachine object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedMachineWithDefaults() *ExpectedMachine {
	this := ExpectedMachine{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ExpectedMachine) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedMachine) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ExpectedMachine) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ExpectedMachine) SetId(v string) {
	o.Id = &v
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *ExpectedMachine) GetSiteId() string {
	if o == nil || IsNil(o.SiteId) {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedMachine) GetSiteIdOk() (*string, bool) {
	if o == nil || IsNil(o.SiteId) {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *ExpectedMachine) HasSiteId() bool {
	if o != nil && !IsNil(o.SiteId) {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *ExpectedMachine) SetSiteId(v string) {
	o.SiteId = &v
}

// GetBmcMacAddress returns the BmcMacAddress field value if set, zero value otherwise.
func (o *ExpectedMachine) GetBmcMacAddress() string {
	if o == nil || IsNil(o.BmcMacAddress) {
		var ret string
		return ret
	}
	return *o.BmcMacAddress
}

// GetBmcMacAddressOk returns a tuple with the BmcMacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedMachine) GetBmcMacAddressOk() (*string, bool) {
	if o == nil || IsNil(o.BmcMacAddress) {
		return nil, false
	}
	return o.BmcMacAddress, true
}

// HasBmcMacAddress returns a boolean if a field has been set.
func (o *ExpectedMachine) HasBmcMacAddress() bool {
	if o != nil && !IsNil(o.BmcMacAddress) {
		return true
	}

	return false
}

// SetBmcMacAddress gets a reference to the given string and assigns it to the BmcMacAddress field.
func (o *ExpectedMachine) SetBmcMacAddress(v string) {
	o.BmcMacAddress = &v
}

// GetChassisSerialNumber returns the ChassisSerialNumber field value if set, zero value otherwise.
func (o *ExpectedMachine) GetChassisSerialNumber() string {
	if o == nil || IsNil(o.ChassisSerialNumber) {
		var ret string
		return ret
	}
	return *o.ChassisSerialNumber
}

// GetChassisSerialNumberOk returns a tuple with the ChassisSerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedMachine) GetChassisSerialNumberOk() (*string, bool) {
	if o == nil || IsNil(o.ChassisSerialNumber) {
		return nil, false
	}
	return o.ChassisSerialNumber, true
}

// HasChassisSerialNumber returns a boolean if a field has been set.
func (o *ExpectedMachine) HasChassisSerialNumber() bool {
	if o != nil && !IsNil(o.ChassisSerialNumber) {
		return true
	}

	return false
}

// SetChassisSerialNumber gets a reference to the given string and assigns it to the ChassisSerialNumber field.
func (o *ExpectedMachine) SetChassisSerialNumber(v string) {
	o.ChassisSerialNumber = &v
}

// GetFallbackDPUSerialNumbers returns the FallbackDPUSerialNumbers field value if set, zero value otherwise.
func (o *ExpectedMachine) GetFallbackDPUSerialNumbers() []string {
	if o == nil || IsNil(o.FallbackDPUSerialNumbers) {
		var ret []string
		return ret
	}
	return o.FallbackDPUSerialNumbers
}

// GetFallbackDPUSerialNumbersOk returns a tuple with the FallbackDPUSerialNumbers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedMachine) GetFallbackDPUSerialNumbersOk() ([]string, bool) {
	if o == nil || IsNil(o.FallbackDPUSerialNumbers) {
		return nil, false
	}
	return o.FallbackDPUSerialNumbers, true
}

// HasFallbackDPUSerialNumbers returns a boolean if a field has been set.
func (o *ExpectedMachine) HasFallbackDPUSerialNumbers() bool {
	if o != nil && !IsNil(o.FallbackDPUSerialNumbers) {
		return true
	}

	return false
}

// SetFallbackDPUSerialNumbers gets a reference to the given []string and assigns it to the FallbackDPUSerialNumbers field.
func (o *ExpectedMachine) SetFallbackDPUSerialNumbers(v []string) {
	o.FallbackDPUSerialNumbers = v
}

// GetSkuId returns the SkuId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachine) GetSkuId() string {
	if o == nil || IsNil(o.SkuId.Get()) {
		var ret string
		return ret
	}
	return *o.SkuId.Get()
}

// GetSkuIdOk returns a tuple with the SkuId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachine) GetSkuIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SkuId.Get(), o.SkuId.IsSet()
}

// HasSkuId returns a boolean if a field has been set.
func (o *ExpectedMachine) HasSkuId() bool {
	if o != nil && o.SkuId.IsSet() {
		return true
	}

	return false
}

// SetSkuId gets a reference to the given NullableString and assigns it to the SkuId field.
func (o *ExpectedMachine) SetSkuId(v string) {
	o.SkuId.Set(&v)
}

// SetSkuIdNil sets the value for SkuId to be an explicit nil
func (o *ExpectedMachine) SetSkuIdNil() {
	o.SkuId.Set(nil)
}

// UnsetSkuId ensures that no value is present for SkuId, not even an explicit nil
func (o *ExpectedMachine) UnsetSkuId() {
	o.SkuId.Unset()
}

// GetSku returns the Sku field value if set, zero value otherwise.
func (o *ExpectedMachine) GetSku() Sku {
	if o == nil || IsNil(o.Sku) {
		var ret Sku
		return ret
	}
	return *o.Sku
}

// GetSkuOk returns a tuple with the Sku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedMachine) GetSkuOk() (*Sku, bool) {
	if o == nil || IsNil(o.Sku) {
		return nil, false
	}
	return o.Sku, true
}

// HasSku returns a boolean if a field has been set.
func (o *ExpectedMachine) HasSku() bool {
	if o != nil && !IsNil(o.Sku) {
		return true
	}

	return false
}

// SetSku gets a reference to the given Sku and assigns it to the Sku field.
func (o *ExpectedMachine) SetSku(v Sku) {
	o.Sku = &v
}

// GetMachineId returns the MachineId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachine) GetMachineId() string {
	if o == nil || IsNil(o.MachineId.Get()) {
		var ret string
		return ret
	}
	return *o.MachineId.Get()
}

// GetMachineIdOk returns a tuple with the MachineId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachine) GetMachineIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MachineId.Get(), o.MachineId.IsSet()
}

// HasMachineId returns a boolean if a field has been set.
func (o *ExpectedMachine) HasMachineId() bool {
	if o != nil && o.MachineId.IsSet() {
		return true
	}

	return false
}

// SetMachineId gets a reference to the given NullableString and assigns it to the MachineId field.
func (o *ExpectedMachine) SetMachineId(v string) {
	o.MachineId.Set(&v)
}

// SetMachineIdNil sets the value for MachineId to be an explicit nil
func (o *ExpectedMachine) SetMachineIdNil() {
	o.MachineId.Set(nil)
}

// UnsetMachineId ensures that no value is present for MachineId, not even an explicit nil
func (o *ExpectedMachine) UnsetMachineId() {
	o.MachineId.Unset()
}

// GetMachine returns the Machine field value if set, zero value otherwise.
func (o *ExpectedMachine) GetMachine() MachineSummary {
	if o == nil || IsNil(o.Machine) {
		var ret MachineSummary
		return ret
	}
	return *o.Machine
}

// GetMachineOk returns a tuple with the Machine field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedMachine) GetMachineOk() (*MachineSummary, bool) {
	if o == nil || IsNil(o.Machine) {
		return nil, false
	}
	return o.Machine, true
}

// HasMachine returns a boolean if a field has been set.
func (o *ExpectedMachine) HasMachine() bool {
	if o != nil && !IsNil(o.Machine) {
		return true
	}

	return false
}

// SetMachine gets a reference to the given MachineSummary and assigns it to the Machine field.
func (o *ExpectedMachine) SetMachine(v MachineSummary) {
	o.Machine = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ExpectedMachine) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedMachine) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ExpectedMachine) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *ExpectedMachine) SetLabels(v map[string]string) {
	o.Labels = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *ExpectedMachine) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedMachine) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *ExpectedMachine) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *ExpectedMachine) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *ExpectedMachine) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedMachine) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *ExpectedMachine) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *ExpectedMachine) SetUpdated(v time.Time) {
	o.Updated = &v
}

func (o ExpectedMachine) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedMachine) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.SiteId) {
		toSerialize["siteId"] = o.SiteId
	}
	if !IsNil(o.BmcMacAddress) {
		toSerialize["bmcMacAddress"] = o.BmcMacAddress
	}
	if !IsNil(o.ChassisSerialNumber) {
		toSerialize["chassisSerialNumber"] = o.ChassisSerialNumber
	}
	if !IsNil(o.FallbackDPUSerialNumbers) {
		toSerialize["fallbackDPUSerialNumbers"] = o.FallbackDPUSerialNumbers
	}
	if o.SkuId.IsSet() {
		toSerialize["skuId"] = o.SkuId.Get()
	}
	if !IsNil(o.Sku) {
		toSerialize["sku"] = o.Sku
	}
	if o.MachineId.IsSet() {
		toSerialize["machineId"] = o.MachineId.Get()
	}
	if !IsNil(o.Machine) {
		toSerialize["machine"] = o.Machine
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

type NullableExpectedMachine struct {
	value *ExpectedMachine
	isSet bool
}

func (v NullableExpectedMachine) Get() *ExpectedMachine {
	return v.value
}

func (v *NullableExpectedMachine) Set(val *ExpectedMachine) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedMachine) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedMachine) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedMachine(val *ExpectedMachine) *NullableExpectedMachine {
	return &NullableExpectedMachine{value: val, isSet: true}
}

func (v NullableExpectedMachine) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedMachine) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
