/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the ExpectedPowerShelfUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedPowerShelfUpdateRequest{}

// ExpectedPowerShelfUpdateRequest Request data to update an existing Expected Power Shelf.  Note: BMC credentials (username/password) are only accepted during creation and updates but are not returned in responses.
type ExpectedPowerShelfUpdateRequest struct {
	// ID of the Expected Power Shelf to update (ignored for single update, used for identification in batch operations).
	Id NullableString `json:"id,omitempty"`
	// MAC address of the Expected Power Shelf's BMC (Baseboard Management Controller)
	BmcMacAddress NullableString `json:"bmcMacAddress,omitempty" validate:"regexp=^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$"`
	// Username for accessing the Expected Power Shelf's BMC
	DefaultBmcUsername NullableString `json:"defaultBmcUsername,omitempty"`
	// Password for accessing the Expected Power Shelf's BMC
	DefaultBmcPassword NullableString `json:"defaultBmcPassword,omitempty"`
	// Serial number of the Expected Power Shelf
	ShelfSerialNumber NullableString `json:"shelfSerialNumber,omitempty"`
	// IP address of the Expected Power Shelf
	IpAddress NullableString    `json:"ipAddress,omitempty"`
	Labels    map[string]string `json:"labels,omitempty"`
}

// NewExpectedPowerShelfUpdateRequest instantiates a new ExpectedPowerShelfUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedPowerShelfUpdateRequest() *ExpectedPowerShelfUpdateRequest {
	this := ExpectedPowerShelfUpdateRequest{}
	return &this
}

// NewExpectedPowerShelfUpdateRequestWithDefaults instantiates a new ExpectedPowerShelfUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedPowerShelfUpdateRequestWithDefaults() *ExpectedPowerShelfUpdateRequest {
	this := ExpectedPowerShelfUpdateRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfUpdateRequest) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfUpdateRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *ExpectedPowerShelfUpdateRequest) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *ExpectedPowerShelfUpdateRequest) SetId(v string) {
	o.Id.Set(&v)
}

// SetIdNil sets the value for Id to be an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) UnsetId() {
	o.Id.Unset()
}

// GetBmcMacAddress returns the BmcMacAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfUpdateRequest) GetBmcMacAddress() string {
	if o == nil || IsNil(o.BmcMacAddress.Get()) {
		var ret string
		return ret
	}
	return *o.BmcMacAddress.Get()
}

// GetBmcMacAddressOk returns a tuple with the BmcMacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfUpdateRequest) GetBmcMacAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BmcMacAddress.Get(), o.BmcMacAddress.IsSet()
}

// HasBmcMacAddress returns a boolean if a field has been set.
func (o *ExpectedPowerShelfUpdateRequest) HasBmcMacAddress() bool {
	if o != nil && o.BmcMacAddress.IsSet() {
		return true
	}

	return false
}

// SetBmcMacAddress gets a reference to the given NullableString and assigns it to the BmcMacAddress field.
func (o *ExpectedPowerShelfUpdateRequest) SetBmcMacAddress(v string) {
	o.BmcMacAddress.Set(&v)
}

// SetBmcMacAddressNil sets the value for BmcMacAddress to be an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) SetBmcMacAddressNil() {
	o.BmcMacAddress.Set(nil)
}

// UnsetBmcMacAddress ensures that no value is present for BmcMacAddress, not even an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) UnsetBmcMacAddress() {
	o.BmcMacAddress.Unset()
}

// GetDefaultBmcUsername returns the DefaultBmcUsername field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfUpdateRequest) GetDefaultBmcUsername() string {
	if o == nil || IsNil(o.DefaultBmcUsername.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultBmcUsername.Get()
}

// GetDefaultBmcUsernameOk returns a tuple with the DefaultBmcUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfUpdateRequest) GetDefaultBmcUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultBmcUsername.Get(), o.DefaultBmcUsername.IsSet()
}

// HasDefaultBmcUsername returns a boolean if a field has been set.
func (o *ExpectedPowerShelfUpdateRequest) HasDefaultBmcUsername() bool {
	if o != nil && o.DefaultBmcUsername.IsSet() {
		return true
	}

	return false
}

// SetDefaultBmcUsername gets a reference to the given NullableString and assigns it to the DefaultBmcUsername field.
func (o *ExpectedPowerShelfUpdateRequest) SetDefaultBmcUsername(v string) {
	o.DefaultBmcUsername.Set(&v)
}

// SetDefaultBmcUsernameNil sets the value for DefaultBmcUsername to be an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) SetDefaultBmcUsernameNil() {
	o.DefaultBmcUsername.Set(nil)
}

// UnsetDefaultBmcUsername ensures that no value is present for DefaultBmcUsername, not even an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) UnsetDefaultBmcUsername() {
	o.DefaultBmcUsername.Unset()
}

// GetDefaultBmcPassword returns the DefaultBmcPassword field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfUpdateRequest) GetDefaultBmcPassword() string {
	if o == nil || IsNil(o.DefaultBmcPassword.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultBmcPassword.Get()
}

// GetDefaultBmcPasswordOk returns a tuple with the DefaultBmcPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfUpdateRequest) GetDefaultBmcPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultBmcPassword.Get(), o.DefaultBmcPassword.IsSet()
}

// HasDefaultBmcPassword returns a boolean if a field has been set.
func (o *ExpectedPowerShelfUpdateRequest) HasDefaultBmcPassword() bool {
	if o != nil && o.DefaultBmcPassword.IsSet() {
		return true
	}

	return false
}

// SetDefaultBmcPassword gets a reference to the given NullableString and assigns it to the DefaultBmcPassword field.
func (o *ExpectedPowerShelfUpdateRequest) SetDefaultBmcPassword(v string) {
	o.DefaultBmcPassword.Set(&v)
}

// SetDefaultBmcPasswordNil sets the value for DefaultBmcPassword to be an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) SetDefaultBmcPasswordNil() {
	o.DefaultBmcPassword.Set(nil)
}

// UnsetDefaultBmcPassword ensures that no value is present for DefaultBmcPassword, not even an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) UnsetDefaultBmcPassword() {
	o.DefaultBmcPassword.Unset()
}

// GetShelfSerialNumber returns the ShelfSerialNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfUpdateRequest) GetShelfSerialNumber() string {
	if o == nil || IsNil(o.ShelfSerialNumber.Get()) {
		var ret string
		return ret
	}
	return *o.ShelfSerialNumber.Get()
}

// GetShelfSerialNumberOk returns a tuple with the ShelfSerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfUpdateRequest) GetShelfSerialNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShelfSerialNumber.Get(), o.ShelfSerialNumber.IsSet()
}

// HasShelfSerialNumber returns a boolean if a field has been set.
func (o *ExpectedPowerShelfUpdateRequest) HasShelfSerialNumber() bool {
	if o != nil && o.ShelfSerialNumber.IsSet() {
		return true
	}

	return false
}

// SetShelfSerialNumber gets a reference to the given NullableString and assigns it to the ShelfSerialNumber field.
func (o *ExpectedPowerShelfUpdateRequest) SetShelfSerialNumber(v string) {
	o.ShelfSerialNumber.Set(&v)
}

// SetShelfSerialNumberNil sets the value for ShelfSerialNumber to be an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) SetShelfSerialNumberNil() {
	o.ShelfSerialNumber.Set(nil)
}

// UnsetShelfSerialNumber ensures that no value is present for ShelfSerialNumber, not even an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) UnsetShelfSerialNumber() {
	o.ShelfSerialNumber.Unset()
}

// GetIpAddress returns the IpAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfUpdateRequest) GetIpAddress() string {
	if o == nil || IsNil(o.IpAddress.Get()) {
		var ret string
		return ret
	}
	return *o.IpAddress.Get()
}

// GetIpAddressOk returns a tuple with the IpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfUpdateRequest) GetIpAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IpAddress.Get(), o.IpAddress.IsSet()
}

// HasIpAddress returns a boolean if a field has been set.
func (o *ExpectedPowerShelfUpdateRequest) HasIpAddress() bool {
	if o != nil && o.IpAddress.IsSet() {
		return true
	}

	return false
}

// SetIpAddress gets a reference to the given NullableString and assigns it to the IpAddress field.
func (o *ExpectedPowerShelfUpdateRequest) SetIpAddress(v string) {
	o.IpAddress.Set(&v)
}

// SetIpAddressNil sets the value for IpAddress to be an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) SetIpAddressNil() {
	o.IpAddress.Set(nil)
}

// UnsetIpAddress ensures that no value is present for IpAddress, not even an explicit nil
func (o *ExpectedPowerShelfUpdateRequest) UnsetIpAddress() {
	o.IpAddress.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ExpectedPowerShelfUpdateRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedPowerShelfUpdateRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ExpectedPowerShelfUpdateRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *ExpectedPowerShelfUpdateRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

func (o ExpectedPowerShelfUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedPowerShelfUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if o.BmcMacAddress.IsSet() {
		toSerialize["bmcMacAddress"] = o.BmcMacAddress.Get()
	}
	if o.DefaultBmcUsername.IsSet() {
		toSerialize["defaultBmcUsername"] = o.DefaultBmcUsername.Get()
	}
	if o.DefaultBmcPassword.IsSet() {
		toSerialize["defaultBmcPassword"] = o.DefaultBmcPassword.Get()
	}
	if o.ShelfSerialNumber.IsSet() {
		toSerialize["shelfSerialNumber"] = o.ShelfSerialNumber.Get()
	}
	if o.IpAddress.IsSet() {
		toSerialize["ipAddress"] = o.IpAddress.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

type NullableExpectedPowerShelfUpdateRequest struct {
	value *ExpectedPowerShelfUpdateRequest
	isSet bool
}

func (v NullableExpectedPowerShelfUpdateRequest) Get() *ExpectedPowerShelfUpdateRequest {
	return v.value
}

func (v *NullableExpectedPowerShelfUpdateRequest) Set(val *ExpectedPowerShelfUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedPowerShelfUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedPowerShelfUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedPowerShelfUpdateRequest(val *ExpectedPowerShelfUpdateRequest) *NullableExpectedPowerShelfUpdateRequest {
	return &NullableExpectedPowerShelfUpdateRequest{value: val, isSet: true}
}

func (v NullableExpectedPowerShelfUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedPowerShelfUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
