/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ExpectedPowerShelfCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedPowerShelfCreateRequest{}

// ExpectedPowerShelfCreateRequest Request data to create a new Expected Power Shelf.  Note: BMC credentials (username/password) are only accepted during creation and updates but are not returned in responses.
type ExpectedPowerShelfCreateRequest struct {
	// ID of the site the Expected Power Shelf belongs to
	SiteId string `json:"siteId"`
	// MAC address of the Expected Power Shelf's BMC (Baseboard Management Controller)
	BmcMacAddress string `json:"bmcMacAddress" validate:"regexp=^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$"`
	// Username for accessing the Expected Power Shelf's BMC
	DefaultBmcUsername NullableString `json:"defaultBmcUsername,omitempty"`
	// Password for accessing the Expected Power Shelf's BMC
	DefaultBmcPassword NullableString `json:"defaultBmcPassword,omitempty"`
	// Serial number of the Expected Power Shelf
	ShelfSerialNumber string `json:"shelfSerialNumber"`
	// IP address of the Expected Power Shelf
	IpAddress NullableString    `json:"ipAddress,omitempty"`
	Labels    map[string]string `json:"labels,omitempty"`
}

type _ExpectedPowerShelfCreateRequest ExpectedPowerShelfCreateRequest

// NewExpectedPowerShelfCreateRequest instantiates a new ExpectedPowerShelfCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedPowerShelfCreateRequest(siteId string, bmcMacAddress string, shelfSerialNumber string) *ExpectedPowerShelfCreateRequest {
	this := ExpectedPowerShelfCreateRequest{}
	this.SiteId = siteId
	this.BmcMacAddress = bmcMacAddress
	this.ShelfSerialNumber = shelfSerialNumber
	return &this
}

// NewExpectedPowerShelfCreateRequestWithDefaults instantiates a new ExpectedPowerShelfCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedPowerShelfCreateRequestWithDefaults() *ExpectedPowerShelfCreateRequest {
	this := ExpectedPowerShelfCreateRequest{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *ExpectedPowerShelfCreateRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *ExpectedPowerShelfCreateRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *ExpectedPowerShelfCreateRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetBmcMacAddress returns the BmcMacAddress field value
func (o *ExpectedPowerShelfCreateRequest) GetBmcMacAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BmcMacAddress
}

// GetBmcMacAddressOk returns a tuple with the BmcMacAddress field value
// and a boolean to check if the value has been set.
func (o *ExpectedPowerShelfCreateRequest) GetBmcMacAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BmcMacAddress, true
}

// SetBmcMacAddress sets field value
func (o *ExpectedPowerShelfCreateRequest) SetBmcMacAddress(v string) {
	o.BmcMacAddress = v
}

// GetDefaultBmcUsername returns the DefaultBmcUsername field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfCreateRequest) GetDefaultBmcUsername() string {
	if o == nil || IsNil(o.DefaultBmcUsername.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultBmcUsername.Get()
}

// GetDefaultBmcUsernameOk returns a tuple with the DefaultBmcUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfCreateRequest) GetDefaultBmcUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultBmcUsername.Get(), o.DefaultBmcUsername.IsSet()
}

// HasDefaultBmcUsername returns a boolean if a field has been set.
func (o *ExpectedPowerShelfCreateRequest) HasDefaultBmcUsername() bool {
	if o != nil && o.DefaultBmcUsername.IsSet() {
		return true
	}

	return false
}

// SetDefaultBmcUsername gets a reference to the given NullableString and assigns it to the DefaultBmcUsername field.
func (o *ExpectedPowerShelfCreateRequest) SetDefaultBmcUsername(v string) {
	o.DefaultBmcUsername.Set(&v)
}

// SetDefaultBmcUsernameNil sets the value for DefaultBmcUsername to be an explicit nil
func (o *ExpectedPowerShelfCreateRequest) SetDefaultBmcUsernameNil() {
	o.DefaultBmcUsername.Set(nil)
}

// UnsetDefaultBmcUsername ensures that no value is present for DefaultBmcUsername, not even an explicit nil
func (o *ExpectedPowerShelfCreateRequest) UnsetDefaultBmcUsername() {
	o.DefaultBmcUsername.Unset()
}

// GetDefaultBmcPassword returns the DefaultBmcPassword field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfCreateRequest) GetDefaultBmcPassword() string {
	if o == nil || IsNil(o.DefaultBmcPassword.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultBmcPassword.Get()
}

// GetDefaultBmcPasswordOk returns a tuple with the DefaultBmcPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfCreateRequest) GetDefaultBmcPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultBmcPassword.Get(), o.DefaultBmcPassword.IsSet()
}

// HasDefaultBmcPassword returns a boolean if a field has been set.
func (o *ExpectedPowerShelfCreateRequest) HasDefaultBmcPassword() bool {
	if o != nil && o.DefaultBmcPassword.IsSet() {
		return true
	}

	return false
}

// SetDefaultBmcPassword gets a reference to the given NullableString and assigns it to the DefaultBmcPassword field.
func (o *ExpectedPowerShelfCreateRequest) SetDefaultBmcPassword(v string) {
	o.DefaultBmcPassword.Set(&v)
}

// SetDefaultBmcPasswordNil sets the value for DefaultBmcPassword to be an explicit nil
func (o *ExpectedPowerShelfCreateRequest) SetDefaultBmcPasswordNil() {
	o.DefaultBmcPassword.Set(nil)
}

// UnsetDefaultBmcPassword ensures that no value is present for DefaultBmcPassword, not even an explicit nil
func (o *ExpectedPowerShelfCreateRequest) UnsetDefaultBmcPassword() {
	o.DefaultBmcPassword.Unset()
}

// GetShelfSerialNumber returns the ShelfSerialNumber field value
func (o *ExpectedPowerShelfCreateRequest) GetShelfSerialNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShelfSerialNumber
}

// GetShelfSerialNumberOk returns a tuple with the ShelfSerialNumber field value
// and a boolean to check if the value has been set.
func (o *ExpectedPowerShelfCreateRequest) GetShelfSerialNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShelfSerialNumber, true
}

// SetShelfSerialNumber sets field value
func (o *ExpectedPowerShelfCreateRequest) SetShelfSerialNumber(v string) {
	o.ShelfSerialNumber = v
}

// GetIpAddress returns the IpAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedPowerShelfCreateRequest) GetIpAddress() string {
	if o == nil || IsNil(o.IpAddress.Get()) {
		var ret string
		return ret
	}
	return *o.IpAddress.Get()
}

// GetIpAddressOk returns a tuple with the IpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedPowerShelfCreateRequest) GetIpAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IpAddress.Get(), o.IpAddress.IsSet()
}

// HasIpAddress returns a boolean if a field has been set.
func (o *ExpectedPowerShelfCreateRequest) HasIpAddress() bool {
	if o != nil && o.IpAddress.IsSet() {
		return true
	}

	return false
}

// SetIpAddress gets a reference to the given NullableString and assigns it to the IpAddress field.
func (o *ExpectedPowerShelfCreateRequest) SetIpAddress(v string) {
	o.IpAddress.Set(&v)
}

// SetIpAddressNil sets the value for IpAddress to be an explicit nil
func (o *ExpectedPowerShelfCreateRequest) SetIpAddressNil() {
	o.IpAddress.Set(nil)
}

// UnsetIpAddress ensures that no value is present for IpAddress, not even an explicit nil
func (o *ExpectedPowerShelfCreateRequest) UnsetIpAddress() {
	o.IpAddress.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ExpectedPowerShelfCreateRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedPowerShelfCreateRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ExpectedPowerShelfCreateRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *ExpectedPowerShelfCreateRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

func (o ExpectedPowerShelfCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedPowerShelfCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	toSerialize["bmcMacAddress"] = o.BmcMacAddress
	if o.DefaultBmcUsername.IsSet() {
		toSerialize["defaultBmcUsername"] = o.DefaultBmcUsername.Get()
	}
	if o.DefaultBmcPassword.IsSet() {
		toSerialize["defaultBmcPassword"] = o.DefaultBmcPassword.Get()
	}
	toSerialize["shelfSerialNumber"] = o.ShelfSerialNumber
	if o.IpAddress.IsSet() {
		toSerialize["ipAddress"] = o.IpAddress.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

func (o *ExpectedPowerShelfCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
		"bmcMacAddress",
		"shelfSerialNumber",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExpectedPowerShelfCreateRequest := _ExpectedPowerShelfCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExpectedPowerShelfCreateRequest)

	if err != nil {
		return err
	}

	*o = ExpectedPowerShelfCreateRequest(varExpectedPowerShelfCreateRequest)

	return err
}

type NullableExpectedPowerShelfCreateRequest struct {
	value *ExpectedPowerShelfCreateRequest
	isSet bool
}

func (v NullableExpectedPowerShelfCreateRequest) Get() *ExpectedPowerShelfCreateRequest {
	return v.value
}

func (v *NullableExpectedPowerShelfCreateRequest) Set(val *ExpectedPowerShelfCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedPowerShelfCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedPowerShelfCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedPowerShelfCreateRequest(val *ExpectedPowerShelfCreateRequest) *NullableExpectedPowerShelfCreateRequest {
	return &NullableExpectedPowerShelfCreateRequest{value: val, isSet: true}
}

func (v NullableExpectedPowerShelfCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedPowerShelfCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
