/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ExpectedSwitchCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedSwitchCreateRequest{}

// ExpectedSwitchCreateRequest Request data to create a new Expected Switch.  Note: BMC and NvOS credentials (username/password) are only accepted during creation and updates but are not returned in responses.
type ExpectedSwitchCreateRequest struct {
	// ID of the site the Expected Switch belongs to
	SiteId string `json:"siteId"`
	// MAC address of the Expected Switch's BMC (Baseboard Management Controller)
	BmcMacAddress string `json:"bmcMacAddress" validate:"regexp=^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$"`
	// Username for accessing the Expected Switch's BMC
	DefaultBmcUsername NullableString `json:"defaultBmcUsername,omitempty"`
	// Password for accessing the Expected Switch's BMC
	DefaultBmcPassword NullableString `json:"defaultBmcPassword,omitempty"`
	// Serial number of the Expected Switch
	SwitchSerialNumber string `json:"switchSerialNumber"`
	// NvOS username for the Expected Switch
	NvOsUsername NullableString `json:"nvOsUsername,omitempty"`
	// NvOS password for the Expected Switch
	NvOsPassword NullableString    `json:"nvOsPassword,omitempty"`
	Labels       map[string]string `json:"labels,omitempty"`
}

type _ExpectedSwitchCreateRequest ExpectedSwitchCreateRequest

// NewExpectedSwitchCreateRequest instantiates a new ExpectedSwitchCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedSwitchCreateRequest(siteId string, bmcMacAddress string, switchSerialNumber string) *ExpectedSwitchCreateRequest {
	this := ExpectedSwitchCreateRequest{}
	this.SiteId = siteId
	this.BmcMacAddress = bmcMacAddress
	this.SwitchSerialNumber = switchSerialNumber
	return &this
}

// NewExpectedSwitchCreateRequestWithDefaults instantiates a new ExpectedSwitchCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedSwitchCreateRequestWithDefaults() *ExpectedSwitchCreateRequest {
	this := ExpectedSwitchCreateRequest{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *ExpectedSwitchCreateRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *ExpectedSwitchCreateRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *ExpectedSwitchCreateRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetBmcMacAddress returns the BmcMacAddress field value
func (o *ExpectedSwitchCreateRequest) GetBmcMacAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BmcMacAddress
}

// GetBmcMacAddressOk returns a tuple with the BmcMacAddress field value
// and a boolean to check if the value has been set.
func (o *ExpectedSwitchCreateRequest) GetBmcMacAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BmcMacAddress, true
}

// SetBmcMacAddress sets field value
func (o *ExpectedSwitchCreateRequest) SetBmcMacAddress(v string) {
	o.BmcMacAddress = v
}

// GetDefaultBmcUsername returns the DefaultBmcUsername field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedSwitchCreateRequest) GetDefaultBmcUsername() string {
	if o == nil || IsNil(o.DefaultBmcUsername.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultBmcUsername.Get()
}

// GetDefaultBmcUsernameOk returns a tuple with the DefaultBmcUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedSwitchCreateRequest) GetDefaultBmcUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultBmcUsername.Get(), o.DefaultBmcUsername.IsSet()
}

// HasDefaultBmcUsername returns a boolean if a field has been set.
func (o *ExpectedSwitchCreateRequest) HasDefaultBmcUsername() bool {
	if o != nil && o.DefaultBmcUsername.IsSet() {
		return true
	}

	return false
}

// SetDefaultBmcUsername gets a reference to the given NullableString and assigns it to the DefaultBmcUsername field.
func (o *ExpectedSwitchCreateRequest) SetDefaultBmcUsername(v string) {
	o.DefaultBmcUsername.Set(&v)
}

// SetDefaultBmcUsernameNil sets the value for DefaultBmcUsername to be an explicit nil
func (o *ExpectedSwitchCreateRequest) SetDefaultBmcUsernameNil() {
	o.DefaultBmcUsername.Set(nil)
}

// UnsetDefaultBmcUsername ensures that no value is present for DefaultBmcUsername, not even an explicit nil
func (o *ExpectedSwitchCreateRequest) UnsetDefaultBmcUsername() {
	o.DefaultBmcUsername.Unset()
}

// GetDefaultBmcPassword returns the DefaultBmcPassword field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedSwitchCreateRequest) GetDefaultBmcPassword() string {
	if o == nil || IsNil(o.DefaultBmcPassword.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultBmcPassword.Get()
}

// GetDefaultBmcPasswordOk returns a tuple with the DefaultBmcPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedSwitchCreateRequest) GetDefaultBmcPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultBmcPassword.Get(), o.DefaultBmcPassword.IsSet()
}

// HasDefaultBmcPassword returns a boolean if a field has been set.
func (o *ExpectedSwitchCreateRequest) HasDefaultBmcPassword() bool {
	if o != nil && o.DefaultBmcPassword.IsSet() {
		return true
	}

	return false
}

// SetDefaultBmcPassword gets a reference to the given NullableString and assigns it to the DefaultBmcPassword field.
func (o *ExpectedSwitchCreateRequest) SetDefaultBmcPassword(v string) {
	o.DefaultBmcPassword.Set(&v)
}

// SetDefaultBmcPasswordNil sets the value for DefaultBmcPassword to be an explicit nil
func (o *ExpectedSwitchCreateRequest) SetDefaultBmcPasswordNil() {
	o.DefaultBmcPassword.Set(nil)
}

// UnsetDefaultBmcPassword ensures that no value is present for DefaultBmcPassword, not even an explicit nil
func (o *ExpectedSwitchCreateRequest) UnsetDefaultBmcPassword() {
	o.DefaultBmcPassword.Unset()
}

// GetSwitchSerialNumber returns the SwitchSerialNumber field value
func (o *ExpectedSwitchCreateRequest) GetSwitchSerialNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SwitchSerialNumber
}

// GetSwitchSerialNumberOk returns a tuple with the SwitchSerialNumber field value
// and a boolean to check if the value has been set.
func (o *ExpectedSwitchCreateRequest) GetSwitchSerialNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SwitchSerialNumber, true
}

// SetSwitchSerialNumber sets field value
func (o *ExpectedSwitchCreateRequest) SetSwitchSerialNumber(v string) {
	o.SwitchSerialNumber = v
}

// GetNvOsUsername returns the NvOsUsername field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedSwitchCreateRequest) GetNvOsUsername() string {
	if o == nil || IsNil(o.NvOsUsername.Get()) {
		var ret string
		return ret
	}
	return *o.NvOsUsername.Get()
}

// GetNvOsUsernameOk returns a tuple with the NvOsUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedSwitchCreateRequest) GetNvOsUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NvOsUsername.Get(), o.NvOsUsername.IsSet()
}

// HasNvOsUsername returns a boolean if a field has been set.
func (o *ExpectedSwitchCreateRequest) HasNvOsUsername() bool {
	if o != nil && o.NvOsUsername.IsSet() {
		return true
	}

	return false
}

// SetNvOsUsername gets a reference to the given NullableString and assigns it to the NvOsUsername field.
func (o *ExpectedSwitchCreateRequest) SetNvOsUsername(v string) {
	o.NvOsUsername.Set(&v)
}

// SetNvOsUsernameNil sets the value for NvOsUsername to be an explicit nil
func (o *ExpectedSwitchCreateRequest) SetNvOsUsernameNil() {
	o.NvOsUsername.Set(nil)
}

// UnsetNvOsUsername ensures that no value is present for NvOsUsername, not even an explicit nil
func (o *ExpectedSwitchCreateRequest) UnsetNvOsUsername() {
	o.NvOsUsername.Unset()
}

// GetNvOsPassword returns the NvOsPassword field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedSwitchCreateRequest) GetNvOsPassword() string {
	if o == nil || IsNil(o.NvOsPassword.Get()) {
		var ret string
		return ret
	}
	return *o.NvOsPassword.Get()
}

// GetNvOsPasswordOk returns a tuple with the NvOsPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedSwitchCreateRequest) GetNvOsPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NvOsPassword.Get(), o.NvOsPassword.IsSet()
}

// HasNvOsPassword returns a boolean if a field has been set.
func (o *ExpectedSwitchCreateRequest) HasNvOsPassword() bool {
	if o != nil && o.NvOsPassword.IsSet() {
		return true
	}

	return false
}

// SetNvOsPassword gets a reference to the given NullableString and assigns it to the NvOsPassword field.
func (o *ExpectedSwitchCreateRequest) SetNvOsPassword(v string) {
	o.NvOsPassword.Set(&v)
}

// SetNvOsPasswordNil sets the value for NvOsPassword to be an explicit nil
func (o *ExpectedSwitchCreateRequest) SetNvOsPasswordNil() {
	o.NvOsPassword.Set(nil)
}

// UnsetNvOsPassword ensures that no value is present for NvOsPassword, not even an explicit nil
func (o *ExpectedSwitchCreateRequest) UnsetNvOsPassword() {
	o.NvOsPassword.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ExpectedSwitchCreateRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedSwitchCreateRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ExpectedSwitchCreateRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *ExpectedSwitchCreateRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

func (o ExpectedSwitchCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedSwitchCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	toSerialize["bmcMacAddress"] = o.BmcMacAddress
	if o.DefaultBmcUsername.IsSet() {
		toSerialize["defaultBmcUsername"] = o.DefaultBmcUsername.Get()
	}
	if o.DefaultBmcPassword.IsSet() {
		toSerialize["defaultBmcPassword"] = o.DefaultBmcPassword.Get()
	}
	toSerialize["switchSerialNumber"] = o.SwitchSerialNumber
	if o.NvOsUsername.IsSet() {
		toSerialize["nvOsUsername"] = o.NvOsUsername.Get()
	}
	if o.NvOsPassword.IsSet() {
		toSerialize["nvOsPassword"] = o.NvOsPassword.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

func (o *ExpectedSwitchCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
		"bmcMacAddress",
		"switchSerialNumber",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExpectedSwitchCreateRequest := _ExpectedSwitchCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExpectedSwitchCreateRequest)

	if err != nil {
		return err
	}

	*o = ExpectedSwitchCreateRequest(varExpectedSwitchCreateRequest)

	return err
}

type NullableExpectedSwitchCreateRequest struct {
	value *ExpectedSwitchCreateRequest
	isSet bool
}

func (v NullableExpectedSwitchCreateRequest) Get() *ExpectedSwitchCreateRequest {
	return v.value
}

func (v *NullableExpectedSwitchCreateRequest) Set(val *ExpectedSwitchCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedSwitchCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedSwitchCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedSwitchCreateRequest(val *ExpectedSwitchCreateRequest) *NullableExpectedSwitchCreateRequest {
	return &NullableExpectedSwitchCreateRequest{value: val, isSet: true}
}

func (v NullableExpectedSwitchCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedSwitchCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
