/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ExpectedMachineCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedMachineCreateRequest{}

// ExpectedMachineCreateRequest Request data to create a new ExpectedMachine.  Note: BMC credentials (username/password) are only accepted during creation and updates but are not returned in responses.
type ExpectedMachineCreateRequest struct {
	// ID of the site the Expected Machine belongs to
	SiteId string `json:"siteId"`
	// MAC address of the Expected Machine's BMC (Baseboard Management Controller)
	BmcMacAddress string `json:"bmcMacAddress" validate:"regexp=^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$"`
	// Username for accessing the Expected Machine's BMC
	BmcUsername NullableString `json:"bmcUsername,omitempty"`
	// Password for accessing the Expected Machine's BMC
	BmcPassword NullableString `json:"bmcPassword,omitempty"`
	// Serial number of the Expected Machine's chassis
	ChassisSerialNumber string `json:"chassisSerialNumber"`
	// Serial numbers of the Expected Machine's fallback DPUs (Data Processing Units)
	FallbackDPUSerialNumbers []string `json:"fallbackDPUSerialNumbers,omitempty"`
	// Optional ID of the SKU to associate with this Expected Machine
	SkuId  NullableString    `json:"skuId,omitempty"`
	Labels map[string]string `json:"labels,omitempty"`
}

type _ExpectedMachineCreateRequest ExpectedMachineCreateRequest

// NewExpectedMachineCreateRequest instantiates a new ExpectedMachineCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedMachineCreateRequest(siteId string, bmcMacAddress string, chassisSerialNumber string) *ExpectedMachineCreateRequest {
	this := ExpectedMachineCreateRequest{}
	this.SiteId = siteId
	this.BmcMacAddress = bmcMacAddress
	this.ChassisSerialNumber = chassisSerialNumber
	return &this
}

// NewExpectedMachineCreateRequestWithDefaults instantiates a new ExpectedMachineCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedMachineCreateRequestWithDefaults() *ExpectedMachineCreateRequest {
	this := ExpectedMachineCreateRequest{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *ExpectedMachineCreateRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *ExpectedMachineCreateRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *ExpectedMachineCreateRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetBmcMacAddress returns the BmcMacAddress field value
func (o *ExpectedMachineCreateRequest) GetBmcMacAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BmcMacAddress
}

// GetBmcMacAddressOk returns a tuple with the BmcMacAddress field value
// and a boolean to check if the value has been set.
func (o *ExpectedMachineCreateRequest) GetBmcMacAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BmcMacAddress, true
}

// SetBmcMacAddress sets field value
func (o *ExpectedMachineCreateRequest) SetBmcMacAddress(v string) {
	o.BmcMacAddress = v
}

// GetBmcUsername returns the BmcUsername field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineCreateRequest) GetBmcUsername() string {
	if o == nil || IsNil(o.BmcUsername.Get()) {
		var ret string
		return ret
	}
	return *o.BmcUsername.Get()
}

// GetBmcUsernameOk returns a tuple with the BmcUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineCreateRequest) GetBmcUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BmcUsername.Get(), o.BmcUsername.IsSet()
}

// HasBmcUsername returns a boolean if a field has been set.
func (o *ExpectedMachineCreateRequest) HasBmcUsername() bool {
	if o != nil && o.BmcUsername.IsSet() {
		return true
	}

	return false
}

// SetBmcUsername gets a reference to the given NullableString and assigns it to the BmcUsername field.
func (o *ExpectedMachineCreateRequest) SetBmcUsername(v string) {
	o.BmcUsername.Set(&v)
}

// SetBmcUsernameNil sets the value for BmcUsername to be an explicit nil
func (o *ExpectedMachineCreateRequest) SetBmcUsernameNil() {
	o.BmcUsername.Set(nil)
}

// UnsetBmcUsername ensures that no value is present for BmcUsername, not even an explicit nil
func (o *ExpectedMachineCreateRequest) UnsetBmcUsername() {
	o.BmcUsername.Unset()
}

// GetBmcPassword returns the BmcPassword field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineCreateRequest) GetBmcPassword() string {
	if o == nil || IsNil(o.BmcPassword.Get()) {
		var ret string
		return ret
	}
	return *o.BmcPassword.Get()
}

// GetBmcPasswordOk returns a tuple with the BmcPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineCreateRequest) GetBmcPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BmcPassword.Get(), o.BmcPassword.IsSet()
}

// HasBmcPassword returns a boolean if a field has been set.
func (o *ExpectedMachineCreateRequest) HasBmcPassword() bool {
	if o != nil && o.BmcPassword.IsSet() {
		return true
	}

	return false
}

// SetBmcPassword gets a reference to the given NullableString and assigns it to the BmcPassword field.
func (o *ExpectedMachineCreateRequest) SetBmcPassword(v string) {
	o.BmcPassword.Set(&v)
}

// SetBmcPasswordNil sets the value for BmcPassword to be an explicit nil
func (o *ExpectedMachineCreateRequest) SetBmcPasswordNil() {
	o.BmcPassword.Set(nil)
}

// UnsetBmcPassword ensures that no value is present for BmcPassword, not even an explicit nil
func (o *ExpectedMachineCreateRequest) UnsetBmcPassword() {
	o.BmcPassword.Unset()
}

// GetChassisSerialNumber returns the ChassisSerialNumber field value
func (o *ExpectedMachineCreateRequest) GetChassisSerialNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChassisSerialNumber
}

// GetChassisSerialNumberOk returns a tuple with the ChassisSerialNumber field value
// and a boolean to check if the value has been set.
func (o *ExpectedMachineCreateRequest) GetChassisSerialNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChassisSerialNumber, true
}

// SetChassisSerialNumber sets field value
func (o *ExpectedMachineCreateRequest) SetChassisSerialNumber(v string) {
	o.ChassisSerialNumber = v
}

// GetFallbackDPUSerialNumbers returns the FallbackDPUSerialNumbers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineCreateRequest) GetFallbackDPUSerialNumbers() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.FallbackDPUSerialNumbers
}

// GetFallbackDPUSerialNumbersOk returns a tuple with the FallbackDPUSerialNumbers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineCreateRequest) GetFallbackDPUSerialNumbersOk() ([]string, bool) {
	if o == nil || IsNil(o.FallbackDPUSerialNumbers) {
		return nil, false
	}
	return o.FallbackDPUSerialNumbers, true
}

// HasFallbackDPUSerialNumbers returns a boolean if a field has been set.
func (o *ExpectedMachineCreateRequest) HasFallbackDPUSerialNumbers() bool {
	if o != nil && !IsNil(o.FallbackDPUSerialNumbers) {
		return true
	}

	return false
}

// SetFallbackDPUSerialNumbers gets a reference to the given []string and assigns it to the FallbackDPUSerialNumbers field.
func (o *ExpectedMachineCreateRequest) SetFallbackDPUSerialNumbers(v []string) {
	o.FallbackDPUSerialNumbers = v
}

// GetSkuId returns the SkuId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExpectedMachineCreateRequest) GetSkuId() string {
	if o == nil || IsNil(o.SkuId.Get()) {
		var ret string
		return ret
	}
	return *o.SkuId.Get()
}

// GetSkuIdOk returns a tuple with the SkuId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExpectedMachineCreateRequest) GetSkuIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SkuId.Get(), o.SkuId.IsSet()
}

// HasSkuId returns a boolean if a field has been set.
func (o *ExpectedMachineCreateRequest) HasSkuId() bool {
	if o != nil && o.SkuId.IsSet() {
		return true
	}

	return false
}

// SetSkuId gets a reference to the given NullableString and assigns it to the SkuId field.
func (o *ExpectedMachineCreateRequest) SetSkuId(v string) {
	o.SkuId.Set(&v)
}

// SetSkuIdNil sets the value for SkuId to be an explicit nil
func (o *ExpectedMachineCreateRequest) SetSkuIdNil() {
	o.SkuId.Set(nil)
}

// UnsetSkuId ensures that no value is present for SkuId, not even an explicit nil
func (o *ExpectedMachineCreateRequest) UnsetSkuId() {
	o.SkuId.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ExpectedMachineCreateRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpectedMachineCreateRequest) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ExpectedMachineCreateRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *ExpectedMachineCreateRequest) SetLabels(v map[string]string) {
	o.Labels = v
}

func (o ExpectedMachineCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedMachineCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	toSerialize["bmcMacAddress"] = o.BmcMacAddress
	if o.BmcUsername.IsSet() {
		toSerialize["bmcUsername"] = o.BmcUsername.Get()
	}
	if o.BmcPassword.IsSet() {
		toSerialize["bmcPassword"] = o.BmcPassword.Get()
	}
	toSerialize["chassisSerialNumber"] = o.ChassisSerialNumber
	if o.FallbackDPUSerialNumbers != nil {
		toSerialize["fallbackDPUSerialNumbers"] = o.FallbackDPUSerialNumbers
	}
	if o.SkuId.IsSet() {
		toSerialize["skuId"] = o.SkuId.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

func (o *ExpectedMachineCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
		"bmcMacAddress",
		"chassisSerialNumber",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExpectedMachineCreateRequest := _ExpectedMachineCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExpectedMachineCreateRequest)

	if err != nil {
		return err
	}

	*o = ExpectedMachineCreateRequest(varExpectedMachineCreateRequest)

	return err
}

type NullableExpectedMachineCreateRequest struct {
	value *ExpectedMachineCreateRequest
	isSet bool
}

func (v NullableExpectedMachineCreateRequest) Get() *ExpectedMachineCreateRequest {
	return v.value
}

func (v *NullableExpectedMachineCreateRequest) Set(val *ExpectedMachineCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedMachineCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedMachineCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedMachineCreateRequest(val *ExpectedMachineCreateRequest) *NullableExpectedMachineCreateRequest {
	return &NullableExpectedMachineCreateRequest{value: val, isSet: true}
}

func (v NullableExpectedMachineCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedMachineCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
