apiVersion: v2
name: carbide-rest-site-agent
description: Helm chart for the Carbide REST site agent
type: application
version: 0.1.2
appVersion: "latest"
keywords:
  - carbide
  - rest
  - site-agent
